### ISSUE TITLE
#awsadminmfa - AWS Administrative accounts don't require MFA

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-meta#19]
From https://mana.mozilla.org/wiki/display/SECURITY/Nubis#Nubis-#awsadminmfa

AWS Administrative accounts don't require MFA

The dev automation team member non-federated user accounts in the stage and prod AWS nubis accounts are not required to have MFA enabled by policy. A compromise of one of these accounts would affect all production products.

Recommendations :

Establish a policy requiring MFA on administrative accounts

**Comment by tinnightcap** [comment]
This is required as per the document here:

https://mana.mozilla.org/wiki/display/EA/Standards+and+Processes

MFA has been enabled for all admins on all accounts.

**Comment by gdestuynder** [comment]
@tinnightcap is this also required (ie accounts can't be used without MFA) or voluntarily following policy document?

If the later, have we audited all current accounts MFA?
If MFA cannot be enforced - do we have an audit process to ensure MFA is always in use?

**Comment by gdestuynder** [comment]
we discussed this on vidyo:
since we can't enforce it at the AWS level for practical reasons, we need to activate securitymonkey for the account to do the auditing

**Comment by gozer** [comment]
Activate security monkey? Does that mean that we have security monkey up and running somewhere already!?

Or are we talking about deploying, running and managing our own security monkey infrastructure?

**Comment by gdestuynder** [comment]
@gene1wood ^^

**Comment by gene1wood** [comment]
Opsec runs a customized instance of Security Monkey which audits all Mozilla AWS accounts (except Cloud Services).

**Comment by gdestuynder** [comment]
@gene1wood need to review row 28 #awsadminmfa after its enabled

**Comment by gene1wood** [comment]
The security controls for this risk are being tracked in #22 as the technology involved affects both how admins use API keys and when MFA is and isn't required
