### ISSUE TITLE
#awsadminrights - Some users have full admin rights in production at all times

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-meta#21]
From https://mana.mozilla.org/wiki/display/SECURITY/Nubis#Nubis-#awsadminrights

Some users have full admin rights in production at all times

The dev automation team members have manually created non-federated AWS acccounts in the stage and prod nubis AWS accounts. These users have \*.\* permissions at all times. At most times these users do not require these overly broad permissions. Compromise of these users accounts would have a greater impact due to these unneeded privileges.

Recommendations :

 - Implement the “Break the Glass” security operations model
 - Enumerate the specific permissions that the dev automation team users need on a daily basis and only increase those permissions during emergencies

**Comment by tinnightcap** [comment]
We have decided to accept this risk in coordination with InfoSec. We are adding some additional monitoring in an effort that is being tracked elsewhere.
