### ISSUE TITLE
#applogging - Application logging implementation plan is undefined

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-meta#23]
From https://mana.mozilla.org/wiki/display/SECURITY/Nubis#Nubis-#applogging

Application logging implementation plan is undefined

It's not yet defined how application logging and log aggregation will work.

Recommendations :

Define a plan in conjunction with opsec for monitoring/response

**Comment by tinnightcap** [comment]
Application needs to define a fluent forwarder for any logs it generates. After that log entries follow existing pathways.

The resolution to this issue is documenting this process.

**Comment by tinnightcap** [comment]
This issue was moved to nubisproject/nubis-docs#124
