### ISSUE TITLE
Ship logs to mozdef

### ISSUE THREAD

**Issue by tinnightcap** [nubisproject/nubis-meta#27]
The logs that get sent to the fluent S3 bucket now need to go to mozdef.

**Comment by gdestuynder** [comment]
Corresponding Infosec entry: https://bugzilla.mozilla.org/show_bug.cgi?id=1207768

**Comment by gozer** [comment]
This is done/enabled for all plan-b-* accounts!

**Comment by tinnightcap** [comment]
Awesome!

**Comment by gdestuynder** [comment]
Corresponding infosec work https://bugzilla.mozilla.org/show_bug.cgi?id=1217518
