### ISSUE TITLE
Establish process to use STS to obtain temporary AWS API credentials for admin users laptops

### ISSUE THREAD

**Issue by gene1wood** [nubisproject/nubis-meta#28]
Instead of keeping AWS API keys on admins laptops and rotating them every 90 days, please use some STS based method to obtain temporary API keys by authenticating with MFA.

https://mana.mozilla.org/wiki/display/EA/Standards+and+Processes

**Comment by gene1wood** [comment]
The current solution has been the policy linked above. "This will be mitigated in the long term through a tool we are planning to adopt soon (to be released)"

**Comment by gozer** [comment]
http://www.infoq.com/presentations/aws-cli-federation

It's pinterest's aeres, IIRC

**Comment by tinnightcap** [comment]
@gene1wood Can you provide a link to this in the RRA? I need to understand the risk level for prioritizing work. - Thanks

**Comment by tinnightcap** [comment]
This is a duplicate of https://github.com/Nubisproject/nubis-meta/issues/22

**Comment by gene1wood** [comment]
Sorry, I missed this question but, yes, you identified the right RRA risk ID and associated bug ( #22 ).
